
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace LBA_2A_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 135> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 112, column 3 to column 10)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 113, column 3 to column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 114, column 3 to column 12)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 115, column 3 to column 18)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 116, column 3 to column 18)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 117, column 3 to column 26)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 122, column 5 to column 29)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 123, column 1 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 124, column 5 to column 31)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 125, column 1 to column 33)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 126, column 1 to column 33)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 127, column 5 to column 45)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 129, column 5 to column 28)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 130, column 5 to column 39)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 131, column 5 to column 30)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 132, column 1 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 133, column 1 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 134, column 5 to column 44)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 136, column 5 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 137, column 1 to column 50)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 138, column 1 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 139, column 1 to column 44)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 140, column 1 to column 44)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 141, column 5 to column 64)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 144, column 10 to column 28)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 145, column 2 to column 42)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 146, column 10 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 147, column 2 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 148, column 2 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 149, column 10 to column 60)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 143, column 16 to line 150, column 2)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 143, column 1 to line 150, column 2)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 165, column 4 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 168, column 6 to column 216)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 167, column 19 to line 169, column 6)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 167, column 5 to line 169, column 6)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 166, column 3 to line 170, column 4)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 154, column 5 to column 42)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 155, column 5 to column 75)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 156, column 5 to column 48)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 157, column 5 to column 58)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 158, column 4 to column 57)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 159, column 5 to column 90)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 161, column 5 to column 89)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 90, column 5 to column 20)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 92, column 31 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 92, column 1 to column 34)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 93, column 18 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 93, column 1 to column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 95, column 5 to column 24)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 96, column 1 to column 31)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 97, column 5 to column 26)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 98, column 1 to column 24)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 99, column 5 to column 40)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 103, column 9 to column 10)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 103, column 1 to column 18)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 106, column 4 to column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 107, column 4 to column 27)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 105, column 15 to line 108, column 2)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 105, column 1 to line 108, column 2)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 122, column 22 to column 23)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 123, column 18 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 124, column 22 to column 23)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 125, column 18 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 126, column 18 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 127, column 22 to column 23)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 165, column 11 to column 12)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 5, column 10 to column 25)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 6, column 10 to column 23)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 7, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 8, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 9, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 10, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 11, column 10 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 13, column 10 to column 42)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 14, column 10 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 15, column 10 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 16, column 10 to column 52)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 17, column 10 to column 34)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 18, column 10 to column 50)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 19, column 10 to column 59)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 21, column 10 to column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 3, column 57 to line 22, column 6)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 27, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 28, column 10 to column 20)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 29, column 10 to column 18)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 30, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 31, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 32, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 33, column 10 to column 22)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 34, column 10 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 36, column 10 to column 31)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 37, column 10 to column 25)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 38, column 10 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 39, column 10 to column 45)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 40, column 10 to column 43)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 41, column 10 to column 57)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 42, column 10 to column 55)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 43, column 10 to column 54)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 45, column 10 to column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 24, column 57 to line 47, column 6)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 51, column 10 to column 17)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 52, column 10 to column 17)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 53, column 10 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 54, column 10 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 55, column 17 to column 25)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 55, column 10 to column 32)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 56, column 10 to column 19)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 57, column 10 to column 24)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 60, column 15 to column 42)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 61, column 15 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 81, column 20 to column 36)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 80, column 20 to line 82, column 16)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 63, column 20 to column 28)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 70, column 22 to column 79)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 71, column 22 to column 81)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 69, column 24 to line 72, column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 66, column 22 to column 79)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 67, column 22 to column 81)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 65, column 36 to line 68, column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 65, column 20 to line 72, column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 73, column 20 to column 81)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 74, column 20 to column 38)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 75, column 20 to column 51)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 77, column 25 to column 41)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 76, column 39 to line 78, column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 76, column 20 to line 78, column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 62, column 24 to line 80, column 16)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 62, column 15 to line 82, column 16)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 59, column 31 to line 83, column 11)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 59, column 10 to line 83, column 11)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 84, column 10 to column 31)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 85, column 10 to column 21)",
 " (in '/Users/khamir/_DecisionMaking/_rlssm/rlssm/rlssm/stan_models/LBA_2A/LBA_2A.stan', line 49, column 118 to line 86, column 6)"};

struct lba_lpdf_functor__ {
  template <bool propto__, typename T0__, typename T1__, typename T2__,
            typename T3__, typename T4__, typename T5__, typename T6__,
            stan::require_eigen_matrix_dynamic_t<T0__>* = nullptr,
            stan::require_col_vector_t<T1__>* = nullptr,
            stan::require_col_vector_t<T2__>* = nullptr,
            stan::require_col_vector_t<T3__>* = nullptr,
            stan::require_col_vector_t<T4__>* = nullptr,
            stan::require_col_vector_t<T5__>* = nullptr,
            stan::require_col_vector_t<T6__>* = nullptr>
  stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
                       stan::value_type_t<T2__>, stan::value_type_t<T3__>,
                       stan::value_type_t<T4__>,
                       stan::promote_args_t<stan::value_type_t<T5__>,
                                            stan::value_type_t<T6__>>>
  operator()(const T0__& RT, const T1__& k, const T2__& sp_trial_var,
             const T3__& drift_cor, const T4__& drift_inc, const T5__& ndt,
             const T6__& s, std::ostream* pstream__) const;
};
struct lba_pdf_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            typename T4__, stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr,
            stan::require_stan_scalar_t<T2__>* = nullptr,
            stan::require_stan_scalar_t<T3__>* = nullptr,
            stan::require_stan_scalar_t<T4__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
  operator()(const T0__& t, const T1__& b, const T2__& A, const T3__& v,
             const T4__& s, std::ostream* pstream__) const;
};
struct lba_cdf_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            typename T4__, stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr,
            stan::require_stan_scalar_t<T2__>* = nullptr,
            stan::require_stan_scalar_t<T3__>* = nullptr,
            stan::require_stan_scalar_t<T4__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
  operator()(const T0__& t, const T1__& b, const T2__& A, const T3__& v,
             const T4__& s, std::ostream* pstream__) const;
};

template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr,
          stan::require_stan_scalar_t<T2__>* = nullptr,
          stan::require_stan_scalar_t<T3__>* = nullptr,
          stan::require_stan_scalar_t<T4__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
  lba_pdf(const T0__& t, const T1__& b, const T2__& A, const T3__& v,
          const T4__& s, std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ b_A_tv_ts = DUMMY_VAR__;
      local_scalar_t__ b_tv_ts = DUMMY_VAR__;
      local_scalar_t__ term_1 = DUMMY_VAR__;
      local_scalar_t__ term_2 = DUMMY_VAR__;
      local_scalar_t__ term_3 = DUMMY_VAR__;
      local_scalar_t__ term_4 = DUMMY_VAR__;
      local_scalar_t__ pdf = DUMMY_VAR__;
      current_statement__ = 75;
      b_A_tv_ts = (((b - A) - (t * v)) / (t * s));
      current_statement__ = 76;
      b_tv_ts = ((b - (t * v)) / (t * s));
      current_statement__ = 77;
      term_1 = (v * stan::math::Phi(b_A_tv_ts));
      current_statement__ = 78;
      term_2 = (s *
                 stan::math::exp(
                   stan::math::normal_log<false>(b_A_tv_ts, 0, 1)));
      current_statement__ = 79;
      term_3 = (v * stan::math::Phi(b_tv_ts));
      current_statement__ = 80;
      term_4 = (s *
                 stan::math::exp(
                   stan::math::normal_log<false>(b_tv_ts, 0, 1)));
      current_statement__ = 81;
      pdf = ((1 / A) * (((-term_1 + term_2) + term_3) - term_4));
      current_statement__ = 82;
      return pdf;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr,
          stan::require_stan_scalar_t<T2__>* = nullptr,
          stan::require_stan_scalar_t<T3__>* = nullptr,
          stan::require_stan_scalar_t<T4__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
  lba_cdf(const T0__& t, const T1__& b, const T2__& A, const T3__& v,
          const T4__& s, std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ b_A_tv = DUMMY_VAR__;
      local_scalar_t__ b_tv = DUMMY_VAR__;
      local_scalar_t__ ts = DUMMY_VAR__;
      local_scalar_t__ term_1 = DUMMY_VAR__;
      local_scalar_t__ term_2 = DUMMY_VAR__;
      local_scalar_t__ term_3 = DUMMY_VAR__;
      local_scalar_t__ term_4 = DUMMY_VAR__;
      local_scalar_t__ cdf = DUMMY_VAR__;
      current_statement__ = 92;
      b_A_tv = ((b - A) - (t * v));
      current_statement__ = 93;
      b_tv = (b - (t * v));
      current_statement__ = 94;
      ts = (t * s);
      current_statement__ = 95;
      term_1 = ((b_A_tv / A) * stan::math::Phi((b_A_tv / ts)));
      current_statement__ = 96;
      term_2 = ((b_tv / A) * stan::math::Phi((b_tv / ts)));
      current_statement__ = 97;
      term_3 = ((ts / A) *
                 stan::math::exp(
                   stan::math::normal_log<false>((b_A_tv / ts), 0, 1)));
      current_statement__ = 98;
      term_4 = ((ts / A) *
                 stan::math::exp(
                   stan::math::normal_log<false>((b_tv / ts), 0, 1)));
      current_statement__ = 99;
      cdf = ((((1 + term_1) - term_2) + term_3) - term_4);
      current_statement__ = 100;
      return cdf;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__, typename T4__, typename T5__, typename T6__,
          stan::require_eigen_matrix_dynamic_t<T0__>* = nullptr,
          stan::require_col_vector_t<T1__>* = nullptr,
          stan::require_col_vector_t<T2__>* = nullptr,
          stan::require_col_vector_t<T3__>* = nullptr,
          stan::require_col_vector_t<T4__>* = nullptr,
          stan::require_col_vector_t<T5__>* = nullptr,
          stan::require_col_vector_t<T6__>* = nullptr>
  stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
                     stan::value_type_t<T2__>, stan::value_type_t<T3__>,
                     stan::value_type_t<T4__>,
                     stan::promote_args_t<stan::value_type_t<T5__>,
                                          stan::value_type_t<T6__>>>
  lba_lpdf(const T0__& RT_arg__, const T1__& k_arg__,
           const T2__& sp_trial_var_arg__, const T3__& drift_cor_arg__,
           const T4__& drift_inc_arg__, const T5__& ndt_arg__,
           const T6__& s_arg__, std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<stan::value_type_t<T0__>,
                                 stan::value_type_t<T1__>,
                                 stan::value_type_t<T2__>,
                                 stan::value_type_t<T3__>,
                                 stan::value_type_t<T4__>,
                                 stan::promote_args_t<stan::value_type_t<T5__>,
                                                      stan::value_type_t<T6__>>>;
    int current_statement__ = 0; 
    const auto& RT = stan::math::to_ref(RT_arg__);
    const auto& k = stan::math::to_ref(k_arg__);
    const auto& sp_trial_var = stan::math::to_ref(sp_trial_var_arg__);
    const auto& drift_cor = stan::math::to_ref(drift_cor_arg__);
    const auto& drift_inc = stan::math::to_ref(drift_inc_arg__);
    const auto& ndt = stan::math::to_ref(ndt_arg__);
    const auto& s = stan::math::to_ref(s_arg__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ t = DUMMY_VAR__;
      local_scalar_t__ b = DUMMY_VAR__;
      local_scalar_t__ cdf = DUMMY_VAR__;
      local_scalar_t__ pdf = DUMMY_VAR__;
      current_statement__ = 106;
      stan::math::validate_non_negative_index("prob", "rows(RT)",
                                              stan::math::rows(RT));
      Eigen::Matrix<local_scalar_t__, -1, 1> prob =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
           stan::math::rows(RT), DUMMY_VAR__);
      local_scalar_t__ out = DUMMY_VAR__;
      local_scalar_t__ prob_neg = DUMMY_VAR__;
      current_statement__ = 131;
      for (int i = 1; i <= stan::math::rows(RT); ++i) {
        current_statement__ = 110;
        b = (stan::model::rvalue(sp_trial_var, "sp_trial_var",
               stan::model::index_uni(i)) +
              stan::model::rvalue(k, "k", stan::model::index_uni(i)));
        current_statement__ = 111;
        t = (stan::model::rvalue(RT, "RT",
               stan::model::index_uni(i), stan::model::index_uni(1)) -
              stan::model::rvalue(ndt, "ndt", stan::model::index_uni(i)));
        current_statement__ = 129;
        if (stan::math::logical_gt(t, 0)) {
          current_statement__ = 114;
          cdf = 1;
          current_statement__ = 121;
          if (stan::math::logical_eq(
                stan::model::rvalue(RT, "RT",
                  stan::model::index_uni(i), stan::model::index_uni(2)), 1)) {
            current_statement__ = 118;
            pdf = lba_pdf(t, b,
                    stan::model::rvalue(sp_trial_var, "sp_trial_var",
                      stan::model::index_uni(i)),
                    stan::model::rvalue(drift_cor, "drift_cor",
                      stan::model::index_uni(i)),
                    stan::model::rvalue(s, "s", stan::model::index_uni(i)), pstream__);
            current_statement__ = 119;
            cdf = (1 -
                    lba_cdf(t, b,
                      stan::model::rvalue(sp_trial_var, "sp_trial_var",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(drift_inc, "drift_inc",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(s, "s", stan::model::index_uni(i)), pstream__));
          } else {
            current_statement__ = 115;
            pdf = lba_pdf(t, b,
                    stan::model::rvalue(sp_trial_var, "sp_trial_var",
                      stan::model::index_uni(i)),
                    stan::model::rvalue(drift_inc, "drift_inc",
                      stan::model::index_uni(i)),
                    stan::model::rvalue(s, "s", stan::model::index_uni(i)), pstream__);
            current_statement__ = 116;
            cdf = (1 -
                    lba_cdf(t, b,
                      stan::model::rvalue(sp_trial_var, "sp_trial_var",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(drift_cor, "drift_cor",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(s, "s", stan::model::index_uni(i)), pstream__));
          }
          current_statement__ = 122;
          prob_neg = (stan::math::Phi(
                        (-stan::model::rvalue(drift_cor, "drift_cor",
                            stan::model::index_uni(i)) /
                          stan::model::rvalue(s, "s",
                            stan::model::index_uni(i)))) *
                       stan::math::Phi(
                         (-stan::model::rvalue(drift_inc, "drift_inc",
                             stan::model::index_uni(i)) /
                           stan::model::rvalue(s, "s",
                             stan::model::index_uni(i)))));
          current_statement__ = 123;
          stan::model::assign(prob, (pdf * cdf),
            "assigning variable prob", stan::model::index_uni(i));
          current_statement__ = 124;
          stan::model::assign(prob,
            (stan::model::rvalue(prob, "prob", stan::model::index_uni(i)) /
              (1 - prob_neg)),
            "assigning variable prob", stan::model::index_uni(i));
          current_statement__ = 127;
          if (stan::math::logical_lt(
                stan::model::rvalue(prob, "prob", stan::model::index_uni(i)),
                1e-10)) {
            current_statement__ = 125;
            stan::model::assign(prob, 1e-10,
              "assigning variable prob", stan::model::index_uni(i));
          } 
        } else {
          current_statement__ = 112;
          stan::model::assign(prob, 1e-10,
            "assigning variable prob", stan::model::index_uni(i));
        }
      }
      current_statement__ = 132;
      out = stan::math::sum(stan::math::log(prob));
      current_statement__ = 133;
      return out;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__, typename T4__, typename T5__, typename T6__,
          stan::require_eigen_matrix_dynamic_t<T0__>*,
          stan::require_col_vector_t<T1__>*,
          stan::require_col_vector_t<T2__>*,
          stan::require_col_vector_t<T3__>*,
          stan::require_col_vector_t<T4__>*,
          stan::require_col_vector_t<T5__>*,
          stan::require_col_vector_t<T6__>*>
stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
                     stan::value_type_t<T2__>, stan::value_type_t<T3__>,
                     stan::value_type_t<T4__>,
                     stan::promote_args_t<stan::value_type_t<T5__>,
                                          stan::value_type_t<T6__>>>
lba_lpdf_functor__::operator()(const T0__& RT, const T1__& k,
                               const T2__& sp_trial_var,
                               const T3__& drift_cor, const T4__& drift_inc,
                               const T5__& ndt, const T6__& s,
                               std::ostream* pstream__)  const
{
  return lba_lpdf<propto__>(RT, k, sp_trial_var, drift_cor, drift_inc, ndt,
           s, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*,
          stan::require_stan_scalar_t<T2__>*,
          stan::require_stan_scalar_t<T3__>*,
          stan::require_stan_scalar_t<T4__>*>
stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
lba_pdf_functor__::operator()(const T0__& t, const T1__& b, const T2__& A,
                              const T3__& v, const T4__& s,
                              std::ostream* pstream__)  const
{
  return lba_pdf(t, b, A, v, s, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*,
          stan::require_stan_scalar_t<T2__>*,
          stan::require_stan_scalar_t<T3__>*,
          stan::require_stan_scalar_t<T4__>*>
stan::promote_args_t<T0__, T1__, T2__, T3__, T4__>
lba_cdf_functor__::operator()(const T0__& t, const T1__& b, const T2__& A,
                              const T3__& v, const T4__& s,
                              std::ostream* pstream__)  const
{
  return lba_cdf(t, b, A, v, s, pstream__);
}

 class LBA_2A_model final : public model_base_crtp<LBA_2A_model> {

 private:
  int N;
  std::vector<int> accuracy;
  std::vector<double> rt;
  Eigen::Matrix<double, -1, 1> k_priors__;
  Eigen::Matrix<double, -1, 1> sp_trial_var_priors__;
  Eigen::Matrix<double, -1, 1> ndt_priors__;
  Eigen::Matrix<double, -1, 1> drift_priors__;
  Eigen::Matrix<double, -1, 1> drift_variability_priors__;
  Eigen::Matrix<double, -1, -1> RT__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> k_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> sp_trial_var_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> ndt_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> drift_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> drift_variability_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> RT{nullptr, 0, 0};
 
 public:
  ~LBA_2A_model() { }
  
  inline std::string model_name() const final { return "LBA_2A_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  LBA_2A_model(stan::io::var_context& context__,
               unsigned int random_seed__ = 0,
               std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "LBA_2A_model_namespace::LBA_2A_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 45;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 45;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("accuracy", "N", N);
      current_statement__ = 47;
      context__.validate_dims("data initialization","accuracy","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      accuracy = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 47;
      accuracy = context__.vals_i("accuracy");
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "accuracy", accuracy, 1);
      current_statement__ = 47;
      stan::math::check_less_or_equal(function__, "accuracy", accuracy, 2);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("rt", "N", N);
      current_statement__ = 49;
      context__.validate_dims("data initialization","rt","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      rt = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 49;
      rt = context__.vals_r("rt");
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "rt", rt, 0);
      current_statement__ = 50;
      context__.validate_dims("data initialization","k_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      k_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&k_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(k_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> k_priors_flat__;
        current_statement__ = 50;
        k_priors_flat__ = context__.vals_r("k_priors");
        current_statement__ = 50;
        pos__ = 1;
        current_statement__ = 50;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 50;
          stan::model::assign(k_priors, k_priors_flat__[(pos__ - 1)],
            "assigning variable k_priors", stan::model::index_uni(sym1__));
          current_statement__ = 50;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 51;
      context__.validate_dims("data initialization","sp_trial_var_priors",
          "double", std::vector<size_t>{static_cast<size_t>(2)});
      sp_trial_var_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&sp_trial_var_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(sp_trial_var_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> sp_trial_var_priors_flat__;
        current_statement__ = 51;
        sp_trial_var_priors_flat__ = context__.vals_r("sp_trial_var_priors");
        current_statement__ = 51;
        pos__ = 1;
        current_statement__ = 51;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 51;
          stan::model::assign(sp_trial_var_priors,
            sp_trial_var_priors_flat__[(pos__ - 1)],
            "assigning variable sp_trial_var_priors", stan::model::index_uni(sym1__));
          current_statement__ = 51;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 52;
      context__.validate_dims("data initialization","ndt_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      ndt_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&ndt_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(ndt_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> ndt_priors_flat__;
        current_statement__ = 52;
        ndt_priors_flat__ = context__.vals_r("ndt_priors");
        current_statement__ = 52;
        pos__ = 1;
        current_statement__ = 52;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 52;
          stan::model::assign(ndt_priors, ndt_priors_flat__[(pos__ - 1)],
            "assigning variable ndt_priors", stan::model::index_uni(sym1__));
          current_statement__ = 52;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 53;
      context__.validate_dims("data initialization","drift_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      drift_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&drift_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(drift_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> drift_priors_flat__;
        current_statement__ = 53;
        drift_priors_flat__ = context__.vals_r("drift_priors");
        current_statement__ = 53;
        pos__ = 1;
        current_statement__ = 53;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 53;
          stan::model::assign(drift_priors, drift_priors_flat__[(pos__ - 1)],
            "assigning variable drift_priors", stan::model::index_uni(sym1__));
          current_statement__ = 53;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 54;
      context__.validate_dims("data initialization",
          "drift_variability_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      drift_variability_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&drift_variability_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(drift_variability_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> drift_variability_priors_flat__;
        current_statement__ = 54;
        drift_variability_priors_flat__ = context__.vals_r("drift_variability_priors");
        current_statement__ = 54;
        pos__ = 1;
        current_statement__ = 54;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 54;
          stan::model::assign(drift_variability_priors,
            drift_variability_priors_flat__[(pos__ - 1)],
            "assigning variable drift_variability_priors", stan::model::index_uni(sym1__));
          current_statement__ = 54;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 55;
      stan::math::validate_non_negative_index("RT", "N", N);
      current_statement__ = 56;
      RT__ = 
        Eigen::Matrix<double, -1, -1>::Constant(N, 2,
          std::numeric_limits<double>::quiet_NaN());
      new (&RT) Eigen::Map<Eigen::Matrix<double, -1, -1>>(RT__.data(), N, 2);
      
      current_statement__ = 60;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 57;
        stan::model::assign(RT,
          stan::model::rvalue(rt, "rt", stan::model::index_uni(n)),
          "assigning variable RT", stan::model::index_uni(n),
                                     stan::model::index_uni(1));
        current_statement__ = 58;
        stan::model::assign(RT,
          stan::model::rvalue(accuracy, "accuracy",
            stan::model::index_uni(n)),
          "assigning variable RT", stan::model::index_uni(n),
                                     stan::model::index_uni(2));
      }
      current_statement__ = 61;
      stan::math::validate_non_negative_index("k_t", "N", N);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("sp_trial_var_t", "N", N);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("ndt_t", "N", N);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("drift_cor_t", "N", N);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("drift_inc_t", "N", N);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("drift_variability_t", "N", N);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "LBA_2A_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 1;
      k = in__.template read<local_scalar_t__>();
      local_scalar_t__ sp_trial_var = DUMMY_VAR__;
      current_statement__ = 2;
      sp_trial_var = in__.template read<local_scalar_t__>();
      local_scalar_t__ ndt = DUMMY_VAR__;
      current_statement__ = 3;
      ndt = in__.template read<local_scalar_t__>();
      local_scalar_t__ drift_cor = DUMMY_VAR__;
      current_statement__ = 4;
      drift_cor = in__.template read<local_scalar_t__>();
      local_scalar_t__ drift_inc = DUMMY_VAR__;
      current_statement__ = 5;
      drift_inc = in__.template read<local_scalar_t__>();
      local_scalar_t__ drift_variability = DUMMY_VAR__;
      current_statement__ = 6;
      drift_variability = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__, -1, 1> k_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> sp_trial_var_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> ndt_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> drift_cor_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> drift_inc_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> drift_variability_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      local_scalar_t__ transf_k = DUMMY_VAR__;
      local_scalar_t__ transf_sp_trial_var = DUMMY_VAR__;
      local_scalar_t__ transf_ndt = DUMMY_VAR__;
      local_scalar_t__ transf_drift_cor = DUMMY_VAR__;
      local_scalar_t__ transf_drift_inc = DUMMY_VAR__;
      local_scalar_t__ transf_drift_variability = DUMMY_VAR__;
      current_statement__ = 19;
      transf_k = stan::math::log((1 + stan::math::exp(k)));
      current_statement__ = 20;
      transf_sp_trial_var = stan::math::log(
                              (1 + stan::math::exp(sp_trial_var)));
      current_statement__ = 21;
      transf_ndt = stan::math::log((1 + stan::math::exp(ndt)));
      current_statement__ = 22;
      transf_drift_cor = stan::math::log((1 + stan::math::exp(drift_cor)));
      current_statement__ = 23;
      transf_drift_inc = stan::math::log((1 + stan::math::exp(drift_inc)));
      current_statement__ = 24;
      transf_drift_variability = stan::math::log(
                                   (1 + stan::math::exp(drift_variability)));
      current_statement__ = 32;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 25;
        stan::model::assign(k_t, transf_k,
          "assigning variable k_t", stan::model::index_uni(n));
        current_statement__ = 26;
        stan::model::assign(sp_trial_var_t, transf_sp_trial_var,
          "assigning variable sp_trial_var_t", stan::model::index_uni(n));
        current_statement__ = 27;
        stan::model::assign(ndt_t, transf_ndt,
          "assigning variable ndt_t", stan::model::index_uni(n));
        current_statement__ = 28;
        stan::model::assign(drift_cor_t, transf_drift_cor,
          "assigning variable drift_cor_t", stan::model::index_uni(n));
        current_statement__ = 29;
        stan::model::assign(drift_inc_t, transf_drift_inc,
          "assigning variable drift_inc_t", stan::model::index_uni(n));
        current_statement__ = 30;
        stan::model::assign(drift_variability_t, transf_drift_variability,
          "assigning variable drift_variability_t", stan::model::index_uni(n));
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "k_t", k_t, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "sp_trial_var_t",
                                            sp_trial_var_t, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "ndt_t", ndt_t, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "drift_cor_t",
                                            drift_cor_t, 0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "drift_inc_t",
                                            drift_inc_t, 0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "drift_variability_t",
                                            drift_variability_t, 0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "transf_k", transf_k, 0);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "transf_sp_trial_var",
                                            transf_sp_trial_var, 0);
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "transf_ndt",
                                            transf_ndt, 0);
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "transf_drift_cor",
                                            transf_drift_cor, 0);
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "transf_drift_inc",
                                            transf_drift_inc, 0);
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "transf_drift_variability",
                                            transf_drift_variability, 0);
      {
        current_statement__ = 38;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(k,
            stan::model::rvalue(k_priors, "k_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(k_priors, "k_priors",
              stan::model::index_uni(2))));
        current_statement__ = 39;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(sp_trial_var,
            stan::model::rvalue(sp_trial_var_priors, "sp_trial_var_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(sp_trial_var_priors, "sp_trial_var_priors",
              stan::model::index_uni(2))));
        current_statement__ = 40;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(ndt,
            stan::model::rvalue(ndt_priors, "ndt_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(ndt_priors, "ndt_priors",
              stan::model::index_uni(2))));
        current_statement__ = 41;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(drift_cor,
            stan::model::rvalue(drift_priors, "drift_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(drift_priors, "drift_priors",
              stan::model::index_uni(2))));
        current_statement__ = 42;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(drift_inc,
            stan::model::rvalue(drift_priors, "drift_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(drift_priors, "drift_priors",
              stan::model::index_uni(2))));
        current_statement__ = 43;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(drift_variability,
            stan::model::rvalue(drift_variability_priors,
              "drift_variability_priors", stan::model::index_uni(1)),
            stan::model::rvalue(drift_variability_priors,
              "drift_variability_priors", stan::model::index_uni(2))));
        current_statement__ = 44;
        lp_accum__.add(
          lba_lpdf<propto__>(RT, k_t, sp_trial_var_t, drift_cor_t,
            drift_inc_t, ndt_t, drift_variability_t, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "LBA_2A_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      k = in__.template read<local_scalar_t__>();
      double sp_trial_var = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sp_trial_var = in__.template read<local_scalar_t__>();
      double ndt = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      ndt = in__.template read<local_scalar_t__>();
      double drift_cor = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      drift_cor = in__.template read<local_scalar_t__>();
      double drift_inc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      drift_inc = in__.template read<local_scalar_t__>();
      double drift_variability = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      drift_variability = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double, -1, 1> k_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> sp_trial_var_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> ndt_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> drift_cor_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> drift_inc_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> drift_variability_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      double transf_k = std::numeric_limits<double>::quiet_NaN();
      double transf_sp_trial_var = std::numeric_limits<double>::quiet_NaN();
      double transf_ndt = std::numeric_limits<double>::quiet_NaN();
      double transf_drift_cor = std::numeric_limits<double>::quiet_NaN();
      double transf_drift_inc = std::numeric_limits<double>::quiet_NaN();
      double transf_drift_variability =
         std::numeric_limits<double>::quiet_NaN();
      out__.write(k);
      out__.write(sp_trial_var);
      out__.write(ndt);
      out__.write(drift_cor);
      out__.write(drift_inc);
      out__.write(drift_variability);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 19;
      transf_k = stan::math::log((1 + stan::math::exp(k)));
      current_statement__ = 20;
      transf_sp_trial_var = stan::math::log(
                              (1 + stan::math::exp(sp_trial_var)));
      current_statement__ = 21;
      transf_ndt = stan::math::log((1 + stan::math::exp(ndt)));
      current_statement__ = 22;
      transf_drift_cor = stan::math::log((1 + stan::math::exp(drift_cor)));
      current_statement__ = 23;
      transf_drift_inc = stan::math::log((1 + stan::math::exp(drift_inc)));
      current_statement__ = 24;
      transf_drift_variability = stan::math::log(
                                   (1 + stan::math::exp(drift_variability)));
      current_statement__ = 32;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 25;
        stan::model::assign(k_t, transf_k,
          "assigning variable k_t", stan::model::index_uni(n));
        current_statement__ = 26;
        stan::model::assign(sp_trial_var_t, transf_sp_trial_var,
          "assigning variable sp_trial_var_t", stan::model::index_uni(n));
        current_statement__ = 27;
        stan::model::assign(ndt_t, transf_ndt,
          "assigning variable ndt_t", stan::model::index_uni(n));
        current_statement__ = 28;
        stan::model::assign(drift_cor_t, transf_drift_cor,
          "assigning variable drift_cor_t", stan::model::index_uni(n));
        current_statement__ = 29;
        stan::model::assign(drift_inc_t, transf_drift_inc,
          "assigning variable drift_inc_t", stan::model::index_uni(n));
        current_statement__ = 30;
        stan::model::assign(drift_variability_t, transf_drift_variability,
          "assigning variable drift_variability_t", stan::model::index_uni(n));
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "k_t", k_t, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "sp_trial_var_t",
                                            sp_trial_var_t, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "ndt_t", ndt_t, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "drift_cor_t",
                                            drift_cor_t, 0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "drift_inc_t",
                                            drift_inc_t, 0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "drift_variability_t",
                                            drift_variability_t, 0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "transf_k", transf_k, 0);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "transf_sp_trial_var",
                                            transf_sp_trial_var, 0);
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "transf_ndt",
                                            transf_ndt, 0);
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "transf_drift_cor",
                                            transf_drift_cor, 0);
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "transf_drift_inc",
                                            transf_drift_inc, 0);
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "transf_drift_variability",
                                            transf_drift_variability, 0);
      if (emit_transformed_parameters__) {
        out__.write(k_t);
        out__.write(sp_trial_var_t);
        out__.write(ndt_t);
        out__.write(drift_cor_t);
        out__.write(drift_inc_t);
        out__.write(drift_variability_t);
        out__.write(transf_k);
        out__.write(transf_sp_trial_var);
        out__.write(transf_ndt);
        out__.write(transf_drift_cor);
        out__.write(transf_drift_inc);
        out__.write(transf_drift_variability);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> log_lik =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      {
        current_statement__ = 36;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 34;
          stan::model::assign(log_lik,
            lba_lpdf<false>(stan::math::block(RT, n, 1, 1, 2),
              stan::math::segment(k_t, n, 1),
              stan::math::segment(sp_trial_var_t, n, 1),
              stan::math::segment(drift_cor_t, n, 1),
              stan::math::segment(drift_inc_t, n, 1),
              stan::math::segment(ndt_t, n, 1),
              stan::math::segment(drift_variability_t, n, 1), pstream__),
            "assigning variable log_lik", stan::model::index_uni(n));
        }
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ k = DUMMY_VAR__;
      k = in__.read<local_scalar_t__>();
      out__.write(k);
      local_scalar_t__ sp_trial_var = DUMMY_VAR__;
      sp_trial_var = in__.read<local_scalar_t__>();
      out__.write(sp_trial_var);
      local_scalar_t__ ndt = DUMMY_VAR__;
      ndt = in__.read<local_scalar_t__>();
      out__.write(ndt);
      local_scalar_t__ drift_cor = DUMMY_VAR__;
      drift_cor = in__.read<local_scalar_t__>();
      out__.write(drift_cor);
      local_scalar_t__ drift_inc = DUMMY_VAR__;
      drift_inc = in__.read<local_scalar_t__>();
      out__.write(drift_inc);
      local_scalar_t__ drift_variability = DUMMY_VAR__;
      drift_variability = in__.read<local_scalar_t__>();
      out__.write(drift_variability);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"k", "sp_trial_var", "ndt",
      "drift_cor", "drift_inc", "drift_variability", "k_t", "sp_trial_var_t",
      "ndt_t", "drift_cor_t", "drift_inc_t", "drift_variability_t",
      "transf_k", "transf_sp_trial_var", "transf_ndt", "transf_drift_cor",
      "transf_drift_inc", "transf_drift_variability", "log_lik"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "sp_trial_var");
    param_names__.emplace_back(std::string() + "ndt");
    param_names__.emplace_back(std::string() + "drift_cor");
    param_names__.emplace_back(std::string() + "drift_inc");
    param_names__.emplace_back(std::string() + "drift_variability");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "k_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "sp_trial_var_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ndt_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_cor_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_inc_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_variability_t" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "transf_k");
      param_names__.emplace_back(std::string() + "transf_sp_trial_var");
      param_names__.emplace_back(std::string() + "transf_ndt");
      param_names__.emplace_back(std::string() + "transf_drift_cor");
      param_names__.emplace_back(std::string() + "transf_drift_inc");
      param_names__.emplace_back(std::string() + "transf_drift_variability");
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "sp_trial_var");
    param_names__.emplace_back(std::string() + "ndt");
    param_names__.emplace_back(std::string() + "drift_cor");
    param_names__.emplace_back(std::string() + "drift_inc");
    param_names__.emplace_back(std::string() + "drift_variability");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "k_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "sp_trial_var_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ndt_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_cor_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_inc_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_variability_t" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "transf_k");
      param_names__.emplace_back(std::string() + "transf_sp_trial_var");
      param_names__.emplace_back(std::string() + "transf_ndt");
      param_names__.emplace_back(std::string() + "transf_drift_cor");
      param_names__.emplace_back(std::string() + "transf_drift_inc");
      param_names__.emplace_back(std::string() + "transf_drift_variability");
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sp_trial_var\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ndt\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_cor\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_inc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_variability\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sp_trial_var_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"ndt_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_cor_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_inc_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_variability_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"transf_k\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_sp_trial_var\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_ndt\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_drift_cor\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_drift_inc\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_drift_variability\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sp_trial_var\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ndt\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_cor\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_inc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_variability\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sp_trial_var_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"ndt_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_cor_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_inc_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_variability_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"transf_k\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_sp_trial_var\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_ndt\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_drift_cor\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_drift_inc\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_drift_variability\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((1 + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = 
  (((((((((((N + N) + N) + N) + N) + N) + 1) + 1) + 1) + 1) + 1) + 1);
      const size_t num_gen_quantities = N;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((1 + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = 
  (((((((((((N + N) + N) + N) + N) + N) + 1) + 1) + 1) + 1) + 1) + 1);
      const size_t num_gen_quantities = N;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 6> names__{"k", "sp_trial_var", "ndt",
      "drift_cor", "drift_inc", "drift_variability"};
      const std::array<Eigen::Index, 6> constrain_param_sizes__{1, 1, 
       1, 1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } using stan_model = LBA_2A_model_namespace::LBA_2A_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return LBA_2A_model_namespace::profiles__;
}

#endif


