
// Code generated by stanc v2.29.2
#include <stan/model/model_header.hpp>
namespace ARDM_2A_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 97> locations_array__ = 
{" (found before start of program)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 74, column 2 to column 17)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 75, column 1 to column 10)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 76, column 2 to column 10)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 77, column 2 to column 10)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 78, column 2 to column 10)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 82, column 1 to column 33)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 83, column 1 to column 33)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 84, column 1 to column 33)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 85, column 1 to column 27)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 87, column 1 to column 32)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 88, column 1 to column 26)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 89, column 2 to column 26)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 90, column 1 to column 25)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 91, column 2 to column 26)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 93, column 1 to column 44)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 94, column 1 to column 32)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 95, column 2 to column 31)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 96, column 1 to column 30)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 97, column 2 to column 31)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 100, column 2 to column 36)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 101, column 2 to column 24)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 102, column 4 to column 101)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 103, column 2 to column 99)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 99, column 16 to line 104, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 99, column 1 to line 104, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 118, column 1 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 121, column 2 to column 154)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 120, column 15 to line 122, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 120, column 1 to line 122, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 119, column 1 to line 123, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 108, column 1 to column 45)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 109, column 1 to column 62)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 110, column 2 to column 42)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 111, column 2 to column 42)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 112, column 2 to column 42)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 114, column 1 to column 57)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 49, column 1 to column 16)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 51, column 31 to column 32)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 51, column 1 to column 34)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 52, column 18 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 52, column 1 to column 21)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 54, column 9 to column 10)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 54, column 2 to column 18)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 55, column 8 to column 9)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 55, column 1 to column 17)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 57, column 1 to column 28)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 58, column 1 to column 22)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 59, column 2 to column 22)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 60, column 2 to column 22)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 61, column 2 to column 22)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 65, column 9 to column 10)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 65, column 1 to column 18)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 68, column 1 to column 18)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 69, column 1 to column 24)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 67, column 15 to line 70, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 67, column 1 to line 70, column 2)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 82, column 18 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 83, column 18 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 84, column 18 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 85, column 18 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 118, column 8 to column 9)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 3, column 10 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 4, column 10 to column 75)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 5, column 10 to column 21)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 2, column 42 to line 6, column 6)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 9, column 10 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 10, column 10 to column 74)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 11, column 10 to column 21)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 8, column 42 to line 12, column 6)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 16, column 10 to column 17)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 17, column 17 to column 25)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 17, column 10 to column 32)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 18, column 10 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 19, column 10 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 20, column 10 to column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 23, column 15 to column 36)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 40, column 20 to column 36)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 39, column 19 to line 41, column 16)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 30, column 20 to column 58)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 31, column 20 to column 62)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 29, column 22 to line 32, column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 26, column 20 to column 58)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 27, column 20 to column 62)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 25, column 34 to line 28, column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 25, column 18 to line 32, column 19)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 33, column 18 to column 36)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 36, column 20 to column 36)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 35, column 35 to line 37, column 17)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 35, column 16 to line 37, column 17)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 24, column 24 to line 38, column 16)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 24, column 15 to line 41, column 16)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 22, column 31 to line 42, column 11)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 22, column 10 to line 42, column 11)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 43, column 10 to column 31)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 44, column 10 to column 21)",
 " (in '/home/andrei/PycharmProjects/rlssm/rlssm/stan_models/ARDM_2A/ARDM_2A.stan', line 14, column 89 to line 45, column 6)"};

struct race_lpdf_functor__ {
  template <bool propto__, typename T0__, typename T1__, typename T2__,
            typename T3__, typename T4__,
            stan::require_eigen_matrix_dynamic_t<T0__>* = nullptr,
            stan::require_col_vector_t<T1__>* = nullptr,
            stan::require_col_vector_t<T2__>* = nullptr,
            stan::require_col_vector_t<T3__>* = nullptr,
            stan::require_col_vector_t<T4__>* = nullptr>
  stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
                       stan::value_type_t<T2__>, stan::value_type_t<T3__>,
                       stan::value_type_t<T4__>>
  operator()(const T0__& RT, const T1__& ndt, const T2__& b,
             const T3__& drift_cor, const T4__& drift_inc,
             std::ostream* pstream__) const;
};
struct race_pdf_functor__ {
  template <typename T0__, typename T1__, typename T2__,
            stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr,
            stan::require_stan_scalar_t<T2__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  operator()(const T0__& t, const T1__& b, const T2__& v,
             std::ostream* pstream__) const;
};
struct race_cdf_functor__ {
  template <typename T0__, typename T1__, typename T2__,
            stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr,
            stan::require_stan_scalar_t<T2__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  operator()(const T0__& t, const T1__& b, const T2__& v,
             std::ostream* pstream__) const;
};

template <typename T0__, typename T1__, typename T2__,
          stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr,
          stan::require_stan_scalar_t<T2__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  race_pdf(const T0__& t, const T1__& b, const T2__& v,
           std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ pdf = DUMMY_VAR__;
      current_statement__ = 63;
      pdf = ((b /
               stan::math::sqrt(
                 ((2 * stan::math::pi()) * stan::math::pow(t, 3)))) *
              stan::math::exp((-stan::math::pow(((v * t) - b), 2) / (2 * t))));
      current_statement__ = 64;
      return pdf;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__,
          stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr,
          stan::require_stan_scalar_t<T2__>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  race_cdf(const T0__& t, const T1__& b, const T2__& v,
           std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ cdf = DUMMY_VAR__;
      current_statement__ = 67;
      cdf = (stan::math::Phi((((v * t) - b) / stan::math::sqrt(t))) +
              (stan::math::exp(((2 * v) * b)) *
                stan::math::Phi((-((v * t) + b) / stan::math::sqrt(t)))));
      current_statement__ = 68;
      return cdf;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__, typename T4__,
          stan::require_eigen_matrix_dynamic_t<T0__>* = nullptr,
          stan::require_col_vector_t<T1__>* = nullptr,
          stan::require_col_vector_t<T2__>* = nullptr,
          stan::require_col_vector_t<T3__>* = nullptr,
          stan::require_col_vector_t<T4__>* = nullptr>
  stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
                     stan::value_type_t<T2__>, stan::value_type_t<T3__>,
                     stan::value_type_t<T4__>>
  race_lpdf(const T0__& RT_arg__, const T1__& ndt_arg__, const T2__& b_arg__,
            const T3__& drift_cor_arg__, const T4__& drift_inc_arg__,
            std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<stan::value_type_t<T0__>,
                                 stan::value_type_t<T1__>,
                                 stan::value_type_t<T2__>,
                                 stan::value_type_t<T3__>,
                                 stan::value_type_t<T4__>>;
    int current_statement__ = 0; 
    const auto& RT = stan::math::to_ref(RT_arg__);
    const auto& ndt = stan::math::to_ref(ndt_arg__);
    const auto& b = stan::math::to_ref(b_arg__);
    const auto& drift_cor = stan::math::to_ref(drift_cor_arg__);
    const auto& drift_inc = stan::math::to_ref(drift_inc_arg__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ t = DUMMY_VAR__;
      current_statement__ = 71;
      stan::math::validate_non_negative_index("prob", "rows(RT)",
                                              stan::math::rows(RT));
      Eigen::Matrix<local_scalar_t__, -1, 1> prob =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
           stan::math::rows(RT), DUMMY_VAR__);
      local_scalar_t__ cdf = DUMMY_VAR__;
      local_scalar_t__ pdf = DUMMY_VAR__;
      local_scalar_t__ out = DUMMY_VAR__;
      current_statement__ = 93;
      for (int i = 1; i <= stan::math::rows(RT); ++i) {
        current_statement__ = 76;
        t = (stan::model::rvalue(RT, "RT",
               stan::model::index_uni(i), stan::model::index_uni(1)) -
              stan::model::rvalue(ndt, "ndt", stan::model::index_uni(i)));
        current_statement__ = 91;
        if (stan::math::logical_gt(t, 0)) {
          current_statement__ = 85;
          if (stan::math::logical_eq(
                stan::model::rvalue(RT, "RT",
                  stan::model::index_uni(i), stan::model::index_uni(2)), 1)) {
            current_statement__ = 82;
            pdf = race_pdf(t,
                    stan::model::rvalue(b, "b", stan::model::index_uni(i)),
                    stan::model::rvalue(drift_cor, "drift_cor",
                      stan::model::index_uni(i)), pstream__);
            current_statement__ = 83;
            cdf = (1 -
                    race_cdf(t,
                      stan::model::rvalue(b, "b", stan::model::index_uni(i)),
                      stan::model::rvalue(drift_inc, "drift_inc",
                        stan::model::index_uni(i)), pstream__));
          } else {
            current_statement__ = 79;
            pdf = race_pdf(t,
                    stan::model::rvalue(b, "b", stan::model::index_uni(i)),
                    stan::model::rvalue(drift_inc, "drift_inc",
                      stan::model::index_uni(i)), pstream__);
            current_statement__ = 80;
            cdf = (1 -
                    race_cdf(t,
                      stan::model::rvalue(b, "b", stan::model::index_uni(i)),
                      stan::model::rvalue(drift_cor, "drift_cor",
                        stan::model::index_uni(i)), pstream__));
          }
          current_statement__ = 86;
          stan::model::assign(prob, (pdf * cdf),
            "assigning variable prob", stan::model::index_uni(i));
          current_statement__ = 89;
          if (stan::math::logical_lt(
                stan::model::rvalue(prob, "prob", stan::model::index_uni(i)),
                1e-10)) {
            current_statement__ = 87;
            stan::model::assign(prob, 1e-10,
              "assigning variable prob", stan::model::index_uni(i));
          } 
        } else {
          current_statement__ = 77;
          stan::model::assign(prob, 1e-10,
            "assigning variable prob", stan::model::index_uni(i));
        }
      }
      current_statement__ = 94;
      out = stan::math::sum(stan::math::log(prob));
      current_statement__ = 95;
      return out;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__, typename T4__,
          stan::require_eigen_matrix_dynamic_t<T0__>*,
          stan::require_col_vector_t<T1__>*,
          stan::require_col_vector_t<T2__>*,
          stan::require_col_vector_t<T3__>*,
          stan::require_col_vector_t<T4__>*>
stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
                     stan::value_type_t<T2__>, stan::value_type_t<T3__>,
                     stan::value_type_t<T4__>>
race_lpdf_functor__::operator()(const T0__& RT, const T1__& ndt,
                                const T2__& b, const T3__& drift_cor,
                                const T4__& drift_inc,
                                std::ostream* pstream__)  const
{
  return race_lpdf<propto__>(RT, ndt, b, drift_cor, drift_inc, pstream__);
}

template <typename T0__, typename T1__, typename T2__,
          stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*,
          stan::require_stan_scalar_t<T2__>*>
stan::promote_args_t<T0__, T1__, T2__>
race_pdf_functor__::operator()(const T0__& t, const T1__& b, const T2__& v,
                               std::ostream* pstream__)  const
{
  return race_pdf(t, b, v, pstream__);
}

template <typename T0__, typename T1__, typename T2__,
          stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*,
          stan::require_stan_scalar_t<T2__>*>
stan::promote_args_t<T0__, T1__, T2__>
race_cdf_functor__::operator()(const T0__& t, const T1__& b, const T2__& v,
                               std::ostream* pstream__)  const
{
  return race_cdf(t, b, v, pstream__);
}

 class ARDM_2A_model final : public model_base_crtp<ARDM_2A_model> {

 private:
  int N;
  std::vector<int> accuracy;
  std::vector<double> rt;
  Eigen::Matrix<double, -1, 1> S_cor__;
  Eigen::Matrix<double, -1, 1> S_inc__;
  Eigen::Matrix<double, -1, 1> threshold_priors__;
  Eigen::Matrix<double, -1, 1> ndt_priors__;
  Eigen::Matrix<double, -1, 1> v0_priors__;
  Eigen::Matrix<double, -1, 1> ws_priors__;
  Eigen::Matrix<double, -1, 1> wd_priors__;
  Eigen::Matrix<double, -1, -1> RT__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> S_cor{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> S_inc{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> threshold_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> ndt_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> v0_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> ws_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> wd_priors{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> RT{nullptr, 0, 0};
 
 public:
  ~ARDM_2A_model() { }
  
  inline std::string model_name() const final { return "ARDM_2A_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.2", "stancflags = "};
  }
  
  
  ARDM_2A_model(stan::io::var_context& context__,
                unsigned int random_seed__ = 0,
                std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "ARDM_2A_model_namespace::ARDM_2A_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 37;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 37;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("accuracy", "N", N);
      current_statement__ = 39;
      context__.validate_dims("data initialization","accuracy","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      accuracy = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 39;
      accuracy = context__.vals_i("accuracy");
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "accuracy", accuracy, 1);
      current_statement__ = 39;
      stan::math::check_less_or_equal(function__, "accuracy", accuracy, 2);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("rt", "N", N);
      current_statement__ = 41;
      context__.validate_dims("data initialization","rt","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      rt = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 41;
      rt = context__.vals_r("rt");
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "rt", rt, 0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("S_cor", "N", N);
      current_statement__ = 43;
      context__.validate_dims("data initialization","S_cor","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      S_cor__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&S_cor) Eigen::Map<Eigen::Matrix<double, -1, 1>>(S_cor__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> S_cor_flat__;
        current_statement__ = 43;
        S_cor_flat__ = context__.vals_r("S_cor");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 43;
          stan::model::assign(S_cor, S_cor_flat__[(pos__ - 1)],
            "assigning variable S_cor", stan::model::index_uni(sym1__));
          current_statement__ = 43;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 44;
      stan::math::validate_non_negative_index("S_inc", "N", N);
      current_statement__ = 45;
      context__.validate_dims("data initialization","S_inc","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      S_inc__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&S_inc) Eigen::Map<Eigen::Matrix<double, -1, 1>>(S_inc__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> S_inc_flat__;
        current_statement__ = 45;
        S_inc_flat__ = context__.vals_r("S_inc");
        current_statement__ = 45;
        pos__ = 1;
        current_statement__ = 45;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 45;
          stan::model::assign(S_inc, S_inc_flat__[(pos__ - 1)],
            "assigning variable S_inc", stan::model::index_uni(sym1__));
          current_statement__ = 45;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 46;
      context__.validate_dims("data initialization","threshold_priors",
          "double", std::vector<size_t>{static_cast<size_t>(2)});
      threshold_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&threshold_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(threshold_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> threshold_priors_flat__;
        current_statement__ = 46;
        threshold_priors_flat__ = context__.vals_r("threshold_priors");
        current_statement__ = 46;
        pos__ = 1;
        current_statement__ = 46;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 46;
          stan::model::assign(threshold_priors,
            threshold_priors_flat__[(pos__ - 1)],
            "assigning variable threshold_priors", stan::model::index_uni(sym1__));
          current_statement__ = 46;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 47;
      context__.validate_dims("data initialization","ndt_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      ndt_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&ndt_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(ndt_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> ndt_priors_flat__;
        current_statement__ = 47;
        ndt_priors_flat__ = context__.vals_r("ndt_priors");
        current_statement__ = 47;
        pos__ = 1;
        current_statement__ = 47;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 47;
          stan::model::assign(ndt_priors, ndt_priors_flat__[(pos__ - 1)],
            "assigning variable ndt_priors", stan::model::index_uni(sym1__));
          current_statement__ = 47;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 48;
      context__.validate_dims("data initialization","v0_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      v0_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&v0_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(v0_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> v0_priors_flat__;
        current_statement__ = 48;
        v0_priors_flat__ = context__.vals_r("v0_priors");
        current_statement__ = 48;
        pos__ = 1;
        current_statement__ = 48;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 48;
          stan::model::assign(v0_priors, v0_priors_flat__[(pos__ - 1)],
            "assigning variable v0_priors", stan::model::index_uni(sym1__));
          current_statement__ = 48;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 49;
      context__.validate_dims("data initialization","ws_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      ws_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&ws_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(ws_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> ws_priors_flat__;
        current_statement__ = 49;
        ws_priors_flat__ = context__.vals_r("ws_priors");
        current_statement__ = 49;
        pos__ = 1;
        current_statement__ = 49;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 49;
          stan::model::assign(ws_priors, ws_priors_flat__[(pos__ - 1)],
            "assigning variable ws_priors", stan::model::index_uni(sym1__));
          current_statement__ = 49;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 50;
      context__.validate_dims("data initialization","wd_priors","double",
           std::vector<size_t>{static_cast<size_t>(2)});
      wd_priors__ = 
        Eigen::Matrix<double, -1, 1>::Constant(2,
          std::numeric_limits<double>::quiet_NaN());
      new (&wd_priors) Eigen::Map<Eigen::Matrix<double, -1, 1>>(wd_priors__.data(), 2);
        
      
      {
        std::vector<local_scalar_t__> wd_priors_flat__;
        current_statement__ = 50;
        wd_priors_flat__ = context__.vals_r("wd_priors");
        current_statement__ = 50;
        pos__ = 1;
        current_statement__ = 50;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 50;
          stan::model::assign(wd_priors, wd_priors_flat__[(pos__ - 1)],
            "assigning variable wd_priors", stan::model::index_uni(sym1__));
          current_statement__ = 50;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 51;
      stan::math::validate_non_negative_index("RT", "N", N);
      current_statement__ = 52;
      RT__ = 
        Eigen::Matrix<double, -1, -1>::Constant(N, 2,
          std::numeric_limits<double>::quiet_NaN());
      new (&RT) Eigen::Map<Eigen::Matrix<double, -1, -1>>(RT__.data(), N, 2);
      
      current_statement__ = 56;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 53;
        stan::model::assign(RT,
          stan::model::rvalue(rt, "rt", stan::model::index_uni(n)),
          "assigning variable RT", stan::model::index_uni(n),
                                     stan::model::index_uni(1));
        current_statement__ = 54;
        stan::model::assign(RT,
          stan::model::rvalue(accuracy, "accuracy",
            stan::model::index_uni(n)),
          "assigning variable RT", stan::model::index_uni(n),
                                     stan::model::index_uni(2));
      }
      current_statement__ = 57;
      stan::math::validate_non_negative_index("drift_cor_t", "N", N);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("drift_inc_t", "N", N);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("threshold_t", "N", N);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("ndt_t", "N", N);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "ARDM_2A_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ threshold = DUMMY_VAR__;
      current_statement__ = 1;
      threshold = in__.template read<local_scalar_t__>();
      local_scalar_t__ ndt = DUMMY_VAR__;
      current_statement__ = 2;
      ndt = in__.template read<local_scalar_t__>();
      local_scalar_t__ v0 = DUMMY_VAR__;
      current_statement__ = 3;
      v0 = in__.template read<local_scalar_t__>();
      local_scalar_t__ ws = DUMMY_VAR__;
      current_statement__ = 4;
      ws = in__.template read<local_scalar_t__>();
      local_scalar_t__ wd = DUMMY_VAR__;
      current_statement__ = 5;
      wd = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__, -1, 1> drift_cor_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> drift_inc_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> threshold_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> ndt_t =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      local_scalar_t__ transf_threshold = DUMMY_VAR__;
      local_scalar_t__ transf_ndt = DUMMY_VAR__;
      local_scalar_t__ transf_v0 = DUMMY_VAR__;
      local_scalar_t__ transf_ws = DUMMY_VAR__;
      local_scalar_t__ transf_wd = DUMMY_VAR__;
      current_statement__ = 15;
      transf_threshold = stan::math::log((1 + stan::math::exp(threshold)));
      current_statement__ = 16;
      transf_ndt = stan::math::log((1 + stan::math::exp(ndt)));
      current_statement__ = 17;
      transf_v0 = stan::math::log((1 + stan::math::exp(v0)));
      current_statement__ = 18;
      transf_ws = stan::math::log((1 + stan::math::exp(ws)));
      current_statement__ = 19;
      transf_wd = stan::math::log((1 + stan::math::exp(wd)));
      current_statement__ = 25;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 20;
        stan::model::assign(threshold_t, transf_threshold,
          "assigning variable threshold_t", stan::model::index_uni(n));
        current_statement__ = 21;
        stan::model::assign(ndt_t, transf_ndt,
          "assigning variable ndt_t", stan::model::index_uni(n));
        current_statement__ = 22;
        stan::model::assign(drift_cor_t,
          ((transf_v0 +
             (transf_wd *
               (stan::model::rvalue(S_cor, "S_cor",
                  stan::model::index_uni(n)) -
                 stan::model::rvalue(S_inc, "S_inc",
                   stan::model::index_uni(n))))) +
            (transf_ws *
              (stan::model::rvalue(S_cor, "S_cor", stan::model::index_uni(n))
                +
                stan::model::rvalue(S_inc, "S_inc",
                  stan::model::index_uni(n))))),
          "assigning variable drift_cor_t", stan::model::index_uni(n));
        current_statement__ = 23;
        stan::model::assign(drift_inc_t,
          ((transf_v0 +
             (transf_wd *
               (stan::model::rvalue(S_inc, "S_inc",
                  stan::model::index_uni(n)) -
                 stan::model::rvalue(S_cor, "S_cor",
                   stan::model::index_uni(n))))) +
            (transf_ws *
              (stan::model::rvalue(S_cor, "S_cor", stan::model::index_uni(n))
                +
                stan::model::rvalue(S_inc, "S_inc",
                  stan::model::index_uni(n))))),
          "assigning variable drift_inc_t", stan::model::index_uni(n));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "drift_cor_t",
                                            drift_cor_t, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "drift_inc_t",
                                            drift_inc_t, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "threshold_t",
                                            threshold_t, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "ndt_t", ndt_t, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "transf_threshold",
                                            transf_threshold, 0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "transf_ndt",
                                            transf_ndt, 0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "transf_v0", transf_v0,
                                            0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "transf_ws", transf_ws,
                                            0);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "transf_wd", transf_wd,
                                            0);
      {
        current_statement__ = 31;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(ndt,
            stan::model::rvalue(ndt_priors, "ndt_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(ndt_priors, "ndt_priors",
              stan::model::index_uni(2))));
        current_statement__ = 32;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(threshold,
            stan::model::rvalue(threshold_priors, "threshold_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(threshold_priors, "threshold_priors",
              stan::model::index_uni(2))));
        current_statement__ = 33;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(v0,
            stan::model::rvalue(v0_priors, "v0_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(v0_priors, "v0_priors",
              stan::model::index_uni(2))));
        current_statement__ = 34;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(ws,
            stan::model::rvalue(ws_priors, "ws_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(ws_priors, "ws_priors",
              stan::model::index_uni(2))));
        current_statement__ = 35;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(wd,
            stan::model::rvalue(wd_priors, "wd_priors",
              stan::model::index_uni(1)),
            stan::model::rvalue(wd_priors, "wd_priors",
              stan::model::index_uni(2))));
        current_statement__ = 36;
        lp_accum__.add(
          race_lpdf<propto__>(RT, ndt_t, threshold_t, drift_cor_t,
            drift_inc_t, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "ARDM_2A_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double threshold = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      threshold = in__.template read<local_scalar_t__>();
      double ndt = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      ndt = in__.template read<local_scalar_t__>();
      double v0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      v0 = in__.template read<local_scalar_t__>();
      double ws = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      ws = in__.template read<local_scalar_t__>();
      double wd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      wd = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double, -1, 1> drift_cor_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> drift_inc_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> threshold_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> ndt_t =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      double transf_threshold = std::numeric_limits<double>::quiet_NaN();
      double transf_ndt = std::numeric_limits<double>::quiet_NaN();
      double transf_v0 = std::numeric_limits<double>::quiet_NaN();
      double transf_ws = std::numeric_limits<double>::quiet_NaN();
      double transf_wd = std::numeric_limits<double>::quiet_NaN();
      out__.write(threshold);
      out__.write(ndt);
      out__.write(v0);
      out__.write(ws);
      out__.write(wd);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 15;
      transf_threshold = stan::math::log((1 + stan::math::exp(threshold)));
      current_statement__ = 16;
      transf_ndt = stan::math::log((1 + stan::math::exp(ndt)));
      current_statement__ = 17;
      transf_v0 = stan::math::log((1 + stan::math::exp(v0)));
      current_statement__ = 18;
      transf_ws = stan::math::log((1 + stan::math::exp(ws)));
      current_statement__ = 19;
      transf_wd = stan::math::log((1 + stan::math::exp(wd)));
      current_statement__ = 25;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 20;
        stan::model::assign(threshold_t, transf_threshold,
          "assigning variable threshold_t", stan::model::index_uni(n));
        current_statement__ = 21;
        stan::model::assign(ndt_t, transf_ndt,
          "assigning variable ndt_t", stan::model::index_uni(n));
        current_statement__ = 22;
        stan::model::assign(drift_cor_t,
          ((transf_v0 +
             (transf_wd *
               (stan::model::rvalue(S_cor, "S_cor",
                  stan::model::index_uni(n)) -
                 stan::model::rvalue(S_inc, "S_inc",
                   stan::model::index_uni(n))))) +
            (transf_ws *
              (stan::model::rvalue(S_cor, "S_cor", stan::model::index_uni(n))
                +
                stan::model::rvalue(S_inc, "S_inc",
                  stan::model::index_uni(n))))),
          "assigning variable drift_cor_t", stan::model::index_uni(n));
        current_statement__ = 23;
        stan::model::assign(drift_inc_t,
          ((transf_v0 +
             (transf_wd *
               (stan::model::rvalue(S_inc, "S_inc",
                  stan::model::index_uni(n)) -
                 stan::model::rvalue(S_cor, "S_cor",
                   stan::model::index_uni(n))))) +
            (transf_ws *
              (stan::model::rvalue(S_cor, "S_cor", stan::model::index_uni(n))
                +
                stan::model::rvalue(S_inc, "S_inc",
                  stan::model::index_uni(n))))),
          "assigning variable drift_inc_t", stan::model::index_uni(n));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "drift_cor_t",
                                            drift_cor_t, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "drift_inc_t",
                                            drift_inc_t, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "threshold_t",
                                            threshold_t, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "ndt_t", ndt_t, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "transf_threshold",
                                            transf_threshold, 0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "transf_ndt",
                                            transf_ndt, 0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "transf_v0", transf_v0,
                                            0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "transf_ws", transf_ws,
                                            0);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "transf_wd", transf_wd,
                                            0);
      if (emit_transformed_parameters__) {
        out__.write(drift_cor_t);
        out__.write(drift_inc_t);
        out__.write(threshold_t);
        out__.write(ndt_t);
        out__.write(transf_threshold);
        out__.write(transf_ndt);
        out__.write(transf_v0);
        out__.write(transf_ws);
        out__.write(transf_wd);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> log_lik =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      {
        current_statement__ = 29;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 27;
          stan::model::assign(log_lik,
            race_lpdf<false>(stan::math::block(RT, n, 1, 1, 2),
              stan::math::segment(ndt_t, n, 1),
              stan::math::segment(threshold_t, n, 1),
              stan::math::segment(drift_cor_t, n, 1),
              stan::math::segment(drift_inc_t, n, 1), pstream__),
            "assigning variable log_lik", stan::model::index_uni(n));
        }
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ threshold = DUMMY_VAR__;
      threshold = in__.read<local_scalar_t__>();
      out__.write(threshold);
      local_scalar_t__ ndt = DUMMY_VAR__;
      ndt = in__.read<local_scalar_t__>();
      out__.write(ndt);
      local_scalar_t__ v0 = DUMMY_VAR__;
      v0 = in__.read<local_scalar_t__>();
      out__.write(v0);
      local_scalar_t__ ws = DUMMY_VAR__;
      ws = in__.read<local_scalar_t__>();
      out__.write(ws);
      local_scalar_t__ wd = DUMMY_VAR__;
      wd = in__.read<local_scalar_t__>();
      out__.write(wd);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"threshold", "ndt", "v0", "ws", "wd",
      "drift_cor_t", "drift_inc_t", "threshold_t", "ndt_t",
      "transf_threshold", "transf_ndt", "transf_v0", "transf_ws",
      "transf_wd", "log_lik"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "threshold");
    param_names__.emplace_back(std::string() + "ndt");
    param_names__.emplace_back(std::string() + "v0");
    param_names__.emplace_back(std::string() + "ws");
    param_names__.emplace_back(std::string() + "wd");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_cor_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_inc_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "threshold_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ndt_t" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "transf_threshold");
      param_names__.emplace_back(std::string() + "transf_ndt");
      param_names__.emplace_back(std::string() + "transf_v0");
      param_names__.emplace_back(std::string() + "transf_ws");
      param_names__.emplace_back(std::string() + "transf_wd");
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "threshold");
    param_names__.emplace_back(std::string() + "ndt");
    param_names__.emplace_back(std::string() + "v0");
    param_names__.emplace_back(std::string() + "ws");
    param_names__.emplace_back(std::string() + "wd");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_cor_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "drift_inc_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "threshold_t" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ndt_t" + '.' + std::to_string(sym1__));
        } 
      }
      param_names__.emplace_back(std::string() + "transf_threshold");
      param_names__.emplace_back(std::string() + "transf_ndt");
      param_names__.emplace_back(std::string() + "transf_v0");
      param_names__.emplace_back(std::string() + "transf_ws");
      param_names__.emplace_back(std::string() + "transf_wd");
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"threshold\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ndt\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"v0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ws\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"wd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_cor_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_inc_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"threshold_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"ndt_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"transf_threshold\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_ndt\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_v0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_ws\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_wd\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"threshold\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ndt\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"v0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ws\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"wd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"drift_cor_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"drift_inc_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"threshold_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"ndt_t\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"transf_threshold\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_ndt\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_v0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_ws\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"transf_wd\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + 1) + 1) + 1);
      const size_t num_transformed = ((((((((N +
                                                                    N) + N) +
                                                                    N) + 1) +
                                                                    1) + 1) +
                                                                    1) + 1);
      const size_t num_gen_quantities = N;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + 1) + 1) + 1);
      const size_t num_transformed = ((((((((N +
                                                                    N) + N) +
                                                                    N) + 1) +
                                                                    1) + 1) +
                                                                    1) + 1);
      const size_t num_gen_quantities = N;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 5> names__{"threshold", "ndt", "v0",
      "ws", "wd"};
      const std::array<Eigen::Index, 5> constrain_param_sizes__{1, 1, 
       1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } using stan_model = ARDM_2A_model_namespace::ARDM_2A_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return ARDM_2A_model_namespace::profiles__;
}

#endif


